version: '3.1'

services:

  eva-postgres:
    image: postgres
    container_name: eva-posgres-database
    environment:
      POSTGRES_DB: evaadmin
      POSTGRES_USER: evaadmin
      POSTGRES_PASSWORD: evaadmin
    ports:
      - 8092:5432

  # Access at http://localhost:8091/
  eva-adminer:
    image: adminer
    ports:
      - 8091:8080